# Aliases

alias "sorafetch"="fastfetch"
alias "tmux"="tmux -2"
alias "cal"="calcurse"
alias "ls"="ls -lah --color"
alias "ll"="y"
alias "cat"="bat"
alias "vi"="vim"
alias "tree"="tree -aC"
alias "clock"="tty-clock -c -C 4"
alias "cmatrix"="cmatrix"
alias "glow"="glow -tal -s /Users/aurorathy/Library/Preferences/glow/nord.json"
alias "grep"="grep --color=auto"
alias "jp2a"="jp2a --colors"
