[manager]

cwd = { fg = "#5e81ac" }

# Hovered

hovered = { reversed = true }
preview_hovered = { underline = true }

# Find 

find_keyword = { fg = "#ebcb8b", bold = true, underline = true }
find_position = { fg = "#b48ead", bg = "reset", bold = true }

# Marker

marker_copied = { fg = "#88c0d0", bg = "#88c0d0" }
marker_cut = { fg = "#bf616a", bg = "#bf616a" }
marker_marked = { fg = "#8fbcbb", bg = "#8fbcbb" }
marker_selected = { fg = "#ebcb8b", bg = "#ebcb8b" }

# Tab

tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count

count_copied = { fg = "#eceff4", bg = "#81a1c1" }
count_cut = { fg = "#eceff4", bg = "#bf616a" }
count_selected = { fg = "#eceff4", bg = "#ebcb8b" }

# Border

border_symbol = "|"
border_style = { fg = "#434c5e" }

# Higlighting

syntext_theme = ""

[status]

separator_open = ""
separator_close = ""
separator_style = { fg = "#eceff4", bg = "#eceff4" }

# Mode

mode_normal = { bg = "#5e81ac", bold = true }
modr_select = { bg = "#bf616a", bold = true }
mode_unset = { bg = "#bf616a", bold = true }

# Progress 

progress_label = { bold = true }
progress_normal = { fg = "#5e81ac", bg = "#2e3440" }
progress_error = { fg = "#bf616a", bg = "#2e3440" }

# Permissions

permissions_t = { fg = "#5e81ac" }
permissions_r = { fg = "#ebcb8b" }
permissions_w = { fg = "#bf616a" }
permissions_x = { fg = "#81a1c1" }
permissions_s = { fg = "#3b4252" }

[select]

active = { fg = "#b48ead" }
inactive = {}

[input]

title = {}
value = {}
selected = { reversed = true }

[completion]


active = { reversed = true }
inactive = {}

# Icons

icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]

title = {}
hovered = { fg = "#b48ead", underline = true }

[which]

cols = 3
mask = { bg = "#2e3440" }
cand = { fg = "#5e81ac" }
rest = { fg = "#3b4252" }
desc = { fg = "#b48ead" }
separator = "  "
separator_style = { fg = "#3b4252" }

[help]

on = { fg = "#5e81ac" }
run = { fg = "#b48ead" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#2e3440", bg = "#8fbcbb"}

[notify]

title_info = { fg = "#5e81ac" }
title_warn = { fg = "#8fbcbb" }
title_error = { fg ="#bf616a" }

# Icons 

icon_info = ""
icon_warn = ""
icon_error = ""

[filetype]

rules = [
 
# Images
  { mime = "image/*", fg = "#5e81ac" },

# Media 
  { mime = "{audio,video}/*", fg = "#81a1c1" },

# Archives
  { mime = "application/*zip", fg = "#bf616a" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#bf616a" },

# Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#5e81ac" },

# Fallback
  { name = "*", fg = "#8fbcbb" },
  { name = "*/", fg = "#81a1c1" }
]


