[general]

import = [
"~/.config/alacritty/themes/nord.toml"
]

[env]

TERM = "xterm-256color"

[window]

padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
blur = false
opacity = 0.9

[font]

size = 17.5
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }

[mouse]

hide_when_typing = true

[cursor]

style = { shape = "Block", blinking = "On" }
